In [13]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

df = pd.DataFrame(np.array([[1,10,1], [2,15,10], [3,20,100], [1,25,1000], [1,30,10000]]))
scaler=StandardScaler()
scaler.fit(df)

print(scaler.transform(df))

[[-0.75       -1.41421356 -0.56853297]
 [ 0.5        -0.70710678 -0.56622936]
 [ 1.75        0.         -0.54319317]
 [-0.75        0.70710678 -0.31283135]
 [-0.75        1.41421356  1.99078685]]
